// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: analysis.proto

package ds.analysis;

public interface AirQualityAnalysisRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:analysis.AirQualityAnalysisRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string start_time = 2;</code>
   */
  java.lang.String getStartTime();
  /**
   * <code>string start_time = 2;</code>
   */
  com.google.protobuf.ByteString
      getStartTimeBytes();

  /**
   * <code>string end_time = 3;</code>
   */
  java.lang.String getEndTime();
  /**
   * <code>string end_time = 3;</code>
   */
  com.google.protobuf.ByteString
      getEndTimeBytes();

  /**
   * <code>string analysis_type = 4;</code>
   */
  java.lang.String getAnalysisType();
  /**
   * <code>string analysis_type = 4;</code>
   */
  com.google.protobuf.ByteString
      getAnalysisTypeBytes();
}
