// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: analysis.proto

package ds.analysis;

public interface AirQualityAnalysisResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:analysis.AirQualityAnalysisResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .analysis.AnalysisData air_quality_data = 1;</code>
   */
  java.util.List<ds.analysis.AnalysisData> 
      getAirQualityDataList();
  /**
   * <code>repeated .analysis.AnalysisData air_quality_data = 1;</code>
   */
  ds.analysis.AnalysisData getAirQualityData(int index);
  /**
   * <code>repeated .analysis.AnalysisData air_quality_data = 1;</code>
   */
  int getAirQualityDataCount();
  /**
   * <code>repeated .analysis.AnalysisData air_quality_data = 1;</code>
   */
  java.util.List<? extends ds.analysis.AnalysisDataOrBuilder> 
      getAirQualityDataOrBuilderList();
  /**
   * <code>repeated .analysis.AnalysisData air_quality_data = 1;</code>
   */
  ds.analysis.AnalysisDataOrBuilder getAirQualityDataOrBuilder(
      int index);
}
