// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: analysis.proto

package ds.analysis;

public interface AnalysisParametersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:analysis.AnalysisParametersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .analysis.AnalysisDataParams analysisResult = 1;</code>
   */
  java.util.List<ds.analysis.AnalysisDataParams> 
      getAnalysisResultList();
  /**
   * <code>repeated .analysis.AnalysisDataParams analysisResult = 1;</code>
   */
  ds.analysis.AnalysisDataParams getAnalysisResult(int index);
  /**
   * <code>repeated .analysis.AnalysisDataParams analysisResult = 1;</code>
   */
  int getAnalysisResultCount();
  /**
   * <code>repeated .analysis.AnalysisDataParams analysisResult = 1;</code>
   */
  java.util.List<? extends ds.analysis.AnalysisDataParamsOrBuilder> 
      getAnalysisResultOrBuilderList();
  /**
   * <code>repeated .analysis.AnalysisDataParams analysisResult = 1;</code>
   */
  ds.analysis.AnalysisDataParamsOrBuilder getAnalysisResultOrBuilder(
      int index);
}
