// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: analysis.proto

package ds.analysis;

public final class AnalysisProto {
  private AnalysisProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_analysis_WaterQualityAnalysisRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_analysis_WaterQualityAnalysisRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_analysis_AirQualityAnalysisRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_analysis_AirQualityAnalysisRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_analysis_WaterQualityAnalysisResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_analysis_WaterQualityAnalysisResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_analysis_AirQualityAnalysisResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_analysis_AirQualityAnalysisResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_analysis_AnalysisData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_analysis_AnalysisData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_analysis_AnalysisParametersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_analysis_AnalysisParametersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_analysis_AnalysisDataParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_analysis_AnalysisDataParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_analysis_AnalysisDataParams_AnalysisResultEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_analysis_AnalysisDataParams_AnalysisResultEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_analysis_AnalysisParametersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_analysis_AnalysisParametersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_analysis_StreamAnalysisDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_analysis_StreamAnalysisDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_analysis_StreamAnalysisDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_analysis_StreamAnalysisDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016analysis.proto\022\010analysis\"l\n\033WaterQuali" +
      "tyAnalysisRequest\022\020\n\010location\030\001 \001(\t\022\022\n\ns" +
      "tart_time\030\002 \001(\t\022\020\n\010end_time\030\003 \001(\t\022\025\n\rana" +
      "lysis_type\030\004 \001(\t\"j\n\031AirQualityAnalysisRe" +
      "quest\022\020\n\010location\030\001 \001(\t\022\022\n\nstart_time\030\002 " +
      "\001(\t\022\020\n\010end_time\030\003 \001(\t\022\025\n\ranalysis_type\030\004" +
      " \001(\t\"R\n\034WaterQualityAnalysisResponse\0222\n\022" +
      "water_quality_data\030\001 \003(\0132\026.analysis.Anal" +
      "ysisData\"N\n\032AirQualityAnalysisResponse\0220" +
      "\n\020air_quality_data\030\001 \003(\0132\026.analysis.Anal" +
      "ysisData\"G\n\014AnalysisData\022\020\n\010location\030\001 \001" +
      "(\t\022\014\n\004time\030\002 \001(\t\022\027\n\017analysis_result\030\003 \001(" +
      "\t\"j\n\031AnalysisParametersRequest\022\020\n\010locati" +
      "on\030\001 \001(\t\022\022\n\nstart_time\030\002 \001(\t\022\020\n\010end_time" +
      "\030\003 \001(\t\022\025\n\ranalysis_type\030\004 \001(\t\"\265\001\n\022Analys" +
      "isDataParams\022\020\n\010location\030\001 \001(\t\022\014\n\004time\030\002" +
      " \001(\t\022H\n\016analysisResult\030\003 \003(\01320.analysis." +
      "AnalysisDataParams.AnalysisResultEntry\0325" +
      "\n\023AnalysisResultEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\001:\0028\001\"R\n\032AnalysisParametersRespo" +
      "nse\0224\n\016analysisResult\030\001 \003(\0132\034.analysis.A" +
      "nalysisDataParams\"V\n\031StreamAnalysisDataR" +
      "equest\022\020\n\010location\030\001 \001(\t\022\020\n\010duration\030\002 \001" +
      "(\005\022\025\n\ranalysis_type\030\003 \001(\t\"S\n\032StreamAnaly" +
      "sisDataResponse\0225\n\017analysis_result\030\001 \003(\013" +
      "2\034.analysis.AnalysisDataParams2\256\003\n\017Analy" +
      "sisService\022j\n\027GetWaterQualityAnalysis\022%." +
      "analysis.WaterQualityAnalysisRequest\032&.a" +
      "nalysis.WaterQualityAnalysisResponse\"\000\022d" +
      "\n\025getAirQualityAnalysis\022#.analysis.AirQu" +
      "alityAnalysisRequest\032$.analysis.AirQuali" +
      "tyAnalysisResponse\"\000\022d\n\025SetAnalysisParam" +
      "eters\022#.analysis.AnalysisParametersReque" +
      "st\032$.analysis.AnalysisParametersResponse" +
      "\"\000\022c\n\022StreamAnalysisData\022#.analysis.Stre" +
      "amAnalysisDataRequest\032$.analysis.StreamA" +
      "nalysisDataResponse\"\0000\001B\036\n\013ds.analysisB\r" +
      "AnalysisProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_analysis_WaterQualityAnalysisRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_analysis_WaterQualityAnalysisRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_analysis_WaterQualityAnalysisRequest_descriptor,
        new java.lang.String[] { "Location", "StartTime", "EndTime", "AnalysisType", });
    internal_static_analysis_AirQualityAnalysisRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_analysis_AirQualityAnalysisRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_analysis_AirQualityAnalysisRequest_descriptor,
        new java.lang.String[] { "Location", "StartTime", "EndTime", "AnalysisType", });
    internal_static_analysis_WaterQualityAnalysisResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_analysis_WaterQualityAnalysisResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_analysis_WaterQualityAnalysisResponse_descriptor,
        new java.lang.String[] { "WaterQualityData", });
    internal_static_analysis_AirQualityAnalysisResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_analysis_AirQualityAnalysisResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_analysis_AirQualityAnalysisResponse_descriptor,
        new java.lang.String[] { "AirQualityData", });
    internal_static_analysis_AnalysisData_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_analysis_AnalysisData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_analysis_AnalysisData_descriptor,
        new java.lang.String[] { "Location", "Time", "AnalysisResult", });
    internal_static_analysis_AnalysisParametersRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_analysis_AnalysisParametersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_analysis_AnalysisParametersRequest_descriptor,
        new java.lang.String[] { "Location", "StartTime", "EndTime", "AnalysisType", });
    internal_static_analysis_AnalysisDataParams_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_analysis_AnalysisDataParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_analysis_AnalysisDataParams_descriptor,
        new java.lang.String[] { "Location", "Time", "AnalysisResult", });
    internal_static_analysis_AnalysisDataParams_AnalysisResultEntry_descriptor =
      internal_static_analysis_AnalysisDataParams_descriptor.getNestedTypes().get(0);
    internal_static_analysis_AnalysisDataParams_AnalysisResultEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_analysis_AnalysisDataParams_AnalysisResultEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_analysis_AnalysisParametersResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_analysis_AnalysisParametersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_analysis_AnalysisParametersResponse_descriptor,
        new java.lang.String[] { "AnalysisResult", });
    internal_static_analysis_StreamAnalysisDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_analysis_StreamAnalysisDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_analysis_StreamAnalysisDataRequest_descriptor,
        new java.lang.String[] { "Location", "Duration", "AnalysisType", });
    internal_static_analysis_StreamAnalysisDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_analysis_StreamAnalysisDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_analysis_StreamAnalysisDataResponse_descriptor,
        new java.lang.String[] { "AnalysisResult", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
