// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: analysis.proto

package ds.analysis;

public interface AnalysisDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:analysis.AnalysisData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string time = 2;</code>
   */
  java.lang.String getTime();
  /**
   * <code>string time = 2;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>string analysis_result = 3;</code>
   */
  java.lang.String getAnalysisResult();
  /**
   * <code>string analysis_result = 3;</code>
   */
  com.google.protobuf.ByteString
      getAnalysisResultBytes();
}
