// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: analysis.proto

package ds.analysis;

public interface StreamAnalysisDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:analysis.StreamAnalysisDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>int32 duration = 2;</code>
   */
  int getDuration();

  /**
   * <code>string analysis_type = 3;</code>
   */
  java.lang.String getAnalysisType();
  /**
   * <code>string analysis_type = 3;</code>
   */
  com.google.protobuf.ByteString
      getAnalysisTypeBytes();
}
