// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: analysis.proto

package ds.analysis;

/**
 * Protobuf type {@code analysis.WaterQualityAnalysisResponse}
 */
public  final class WaterQualityAnalysisResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:analysis.WaterQualityAnalysisResponse)
    WaterQualityAnalysisResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WaterQualityAnalysisResponse.newBuilder() to construct.
  private WaterQualityAnalysisResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WaterQualityAnalysisResponse() {
    waterQualityData_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WaterQualityAnalysisResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              waterQualityData_ = new java.util.ArrayList<ds.analysis.AnalysisData>();
              mutable_bitField0_ |= 0x00000001;
            }
            waterQualityData_.add(
                input.readMessage(ds.analysis.AnalysisData.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        waterQualityData_ = java.util.Collections.unmodifiableList(waterQualityData_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.analysis.AnalysisProto.internal_static_analysis_WaterQualityAnalysisResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.analysis.AnalysisProto.internal_static_analysis_WaterQualityAnalysisResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.analysis.WaterQualityAnalysisResponse.class, ds.analysis.WaterQualityAnalysisResponse.Builder.class);
  }

  public static final int WATER_QUALITY_DATA_FIELD_NUMBER = 1;
  private java.util.List<ds.analysis.AnalysisData> waterQualityData_;
  /**
   * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
   */
  public java.util.List<ds.analysis.AnalysisData> getWaterQualityDataList() {
    return waterQualityData_;
  }
  /**
   * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
   */
  public java.util.List<? extends ds.analysis.AnalysisDataOrBuilder> 
      getWaterQualityDataOrBuilderList() {
    return waterQualityData_;
  }
  /**
   * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
   */
  public int getWaterQualityDataCount() {
    return waterQualityData_.size();
  }
  /**
   * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
   */
  public ds.analysis.AnalysisData getWaterQualityData(int index) {
    return waterQualityData_.get(index);
  }
  /**
   * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
   */
  public ds.analysis.AnalysisDataOrBuilder getWaterQualityDataOrBuilder(
      int index) {
    return waterQualityData_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < waterQualityData_.size(); i++) {
      output.writeMessage(1, waterQualityData_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < waterQualityData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, waterQualityData_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.analysis.WaterQualityAnalysisResponse)) {
      return super.equals(obj);
    }
    ds.analysis.WaterQualityAnalysisResponse other = (ds.analysis.WaterQualityAnalysisResponse) obj;

    boolean result = true;
    result = result && getWaterQualityDataList()
        .equals(other.getWaterQualityDataList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getWaterQualityDataCount() > 0) {
      hash = (37 * hash) + WATER_QUALITY_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getWaterQualityDataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.analysis.WaterQualityAnalysisResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.analysis.WaterQualityAnalysisResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.analysis.WaterQualityAnalysisResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.analysis.WaterQualityAnalysisResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.analysis.WaterQualityAnalysisResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.analysis.WaterQualityAnalysisResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.analysis.WaterQualityAnalysisResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.analysis.WaterQualityAnalysisResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.analysis.WaterQualityAnalysisResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.analysis.WaterQualityAnalysisResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.analysis.WaterQualityAnalysisResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.analysis.WaterQualityAnalysisResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.analysis.WaterQualityAnalysisResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code analysis.WaterQualityAnalysisResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:analysis.WaterQualityAnalysisResponse)
      ds.analysis.WaterQualityAnalysisResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.analysis.AnalysisProto.internal_static_analysis_WaterQualityAnalysisResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.analysis.AnalysisProto.internal_static_analysis_WaterQualityAnalysisResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.analysis.WaterQualityAnalysisResponse.class, ds.analysis.WaterQualityAnalysisResponse.Builder.class);
    }

    // Construct using ds.analysis.WaterQualityAnalysisResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getWaterQualityDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (waterQualityDataBuilder_ == null) {
        waterQualityData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        waterQualityDataBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.analysis.AnalysisProto.internal_static_analysis_WaterQualityAnalysisResponse_descriptor;
    }

    @java.lang.Override
    public ds.analysis.WaterQualityAnalysisResponse getDefaultInstanceForType() {
      return ds.analysis.WaterQualityAnalysisResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.analysis.WaterQualityAnalysisResponse build() {
      ds.analysis.WaterQualityAnalysisResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.analysis.WaterQualityAnalysisResponse buildPartial() {
      ds.analysis.WaterQualityAnalysisResponse result = new ds.analysis.WaterQualityAnalysisResponse(this);
      int from_bitField0_ = bitField0_;
      if (waterQualityDataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          waterQualityData_ = java.util.Collections.unmodifiableList(waterQualityData_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.waterQualityData_ = waterQualityData_;
      } else {
        result.waterQualityData_ = waterQualityDataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.analysis.WaterQualityAnalysisResponse) {
        return mergeFrom((ds.analysis.WaterQualityAnalysisResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.analysis.WaterQualityAnalysisResponse other) {
      if (other == ds.analysis.WaterQualityAnalysisResponse.getDefaultInstance()) return this;
      if (waterQualityDataBuilder_ == null) {
        if (!other.waterQualityData_.isEmpty()) {
          if (waterQualityData_.isEmpty()) {
            waterQualityData_ = other.waterQualityData_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureWaterQualityDataIsMutable();
            waterQualityData_.addAll(other.waterQualityData_);
          }
          onChanged();
        }
      } else {
        if (!other.waterQualityData_.isEmpty()) {
          if (waterQualityDataBuilder_.isEmpty()) {
            waterQualityDataBuilder_.dispose();
            waterQualityDataBuilder_ = null;
            waterQualityData_ = other.waterQualityData_;
            bitField0_ = (bitField0_ & ~0x00000001);
            waterQualityDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getWaterQualityDataFieldBuilder() : null;
          } else {
            waterQualityDataBuilder_.addAllMessages(other.waterQualityData_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.analysis.WaterQualityAnalysisResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.analysis.WaterQualityAnalysisResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<ds.analysis.AnalysisData> waterQualityData_ =
      java.util.Collections.emptyList();
    private void ensureWaterQualityDataIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        waterQualityData_ = new java.util.ArrayList<ds.analysis.AnalysisData>(waterQualityData_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ds.analysis.AnalysisData, ds.analysis.AnalysisData.Builder, ds.analysis.AnalysisDataOrBuilder> waterQualityDataBuilder_;

    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public java.util.List<ds.analysis.AnalysisData> getWaterQualityDataList() {
      if (waterQualityDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(waterQualityData_);
      } else {
        return waterQualityDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public int getWaterQualityDataCount() {
      if (waterQualityDataBuilder_ == null) {
        return waterQualityData_.size();
      } else {
        return waterQualityDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public ds.analysis.AnalysisData getWaterQualityData(int index) {
      if (waterQualityDataBuilder_ == null) {
        return waterQualityData_.get(index);
      } else {
        return waterQualityDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public Builder setWaterQualityData(
        int index, ds.analysis.AnalysisData value) {
      if (waterQualityDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWaterQualityDataIsMutable();
        waterQualityData_.set(index, value);
        onChanged();
      } else {
        waterQualityDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public Builder setWaterQualityData(
        int index, ds.analysis.AnalysisData.Builder builderForValue) {
      if (waterQualityDataBuilder_ == null) {
        ensureWaterQualityDataIsMutable();
        waterQualityData_.set(index, builderForValue.build());
        onChanged();
      } else {
        waterQualityDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public Builder addWaterQualityData(ds.analysis.AnalysisData value) {
      if (waterQualityDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWaterQualityDataIsMutable();
        waterQualityData_.add(value);
        onChanged();
      } else {
        waterQualityDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public Builder addWaterQualityData(
        int index, ds.analysis.AnalysisData value) {
      if (waterQualityDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWaterQualityDataIsMutable();
        waterQualityData_.add(index, value);
        onChanged();
      } else {
        waterQualityDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public Builder addWaterQualityData(
        ds.analysis.AnalysisData.Builder builderForValue) {
      if (waterQualityDataBuilder_ == null) {
        ensureWaterQualityDataIsMutable();
        waterQualityData_.add(builderForValue.build());
        onChanged();
      } else {
        waterQualityDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public Builder addWaterQualityData(
        int index, ds.analysis.AnalysisData.Builder builderForValue) {
      if (waterQualityDataBuilder_ == null) {
        ensureWaterQualityDataIsMutable();
        waterQualityData_.add(index, builderForValue.build());
        onChanged();
      } else {
        waterQualityDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public Builder addAllWaterQualityData(
        java.lang.Iterable<? extends ds.analysis.AnalysisData> values) {
      if (waterQualityDataBuilder_ == null) {
        ensureWaterQualityDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, waterQualityData_);
        onChanged();
      } else {
        waterQualityDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public Builder clearWaterQualityData() {
      if (waterQualityDataBuilder_ == null) {
        waterQualityData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        waterQualityDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public Builder removeWaterQualityData(int index) {
      if (waterQualityDataBuilder_ == null) {
        ensureWaterQualityDataIsMutable();
        waterQualityData_.remove(index);
        onChanged();
      } else {
        waterQualityDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public ds.analysis.AnalysisData.Builder getWaterQualityDataBuilder(
        int index) {
      return getWaterQualityDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public ds.analysis.AnalysisDataOrBuilder getWaterQualityDataOrBuilder(
        int index) {
      if (waterQualityDataBuilder_ == null) {
        return waterQualityData_.get(index);  } else {
        return waterQualityDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public java.util.List<? extends ds.analysis.AnalysisDataOrBuilder> 
         getWaterQualityDataOrBuilderList() {
      if (waterQualityDataBuilder_ != null) {
        return waterQualityDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(waterQualityData_);
      }
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public ds.analysis.AnalysisData.Builder addWaterQualityDataBuilder() {
      return getWaterQualityDataFieldBuilder().addBuilder(
          ds.analysis.AnalysisData.getDefaultInstance());
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public ds.analysis.AnalysisData.Builder addWaterQualityDataBuilder(
        int index) {
      return getWaterQualityDataFieldBuilder().addBuilder(
          index, ds.analysis.AnalysisData.getDefaultInstance());
    }
    /**
     * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
     */
    public java.util.List<ds.analysis.AnalysisData.Builder> 
         getWaterQualityDataBuilderList() {
      return getWaterQualityDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ds.analysis.AnalysisData, ds.analysis.AnalysisData.Builder, ds.analysis.AnalysisDataOrBuilder> 
        getWaterQualityDataFieldBuilder() {
      if (waterQualityDataBuilder_ == null) {
        waterQualityDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ds.analysis.AnalysisData, ds.analysis.AnalysisData.Builder, ds.analysis.AnalysisDataOrBuilder>(
                waterQualityData_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        waterQualityData_ = null;
      }
      return waterQualityDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:analysis.WaterQualityAnalysisResponse)
  }

  // @@protoc_insertion_point(class_scope:analysis.WaterQualityAnalysisResponse)
  private static final ds.analysis.WaterQualityAnalysisResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.analysis.WaterQualityAnalysisResponse();
  }

  public static ds.analysis.WaterQualityAnalysisResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WaterQualityAnalysisResponse>
      PARSER = new com.google.protobuf.AbstractParser<WaterQualityAnalysisResponse>() {
    @java.lang.Override
    public WaterQualityAnalysisResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WaterQualityAnalysisResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WaterQualityAnalysisResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WaterQualityAnalysisResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.analysis.WaterQualityAnalysisResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

