// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: analysis.proto

package ds.analysis;

public interface WaterQualityAnalysisResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:analysis.WaterQualityAnalysisResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
   */
  java.util.List<ds.analysis.AnalysisData> 
      getWaterQualityDataList();
  /**
   * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
   */
  ds.analysis.AnalysisData getWaterQualityData(int index);
  /**
   * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
   */
  int getWaterQualityDataCount();
  /**
   * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
   */
  java.util.List<? extends ds.analysis.AnalysisDataOrBuilder> 
      getWaterQualityDataOrBuilderList();
  /**
   * <code>repeated .analysis.AnalysisData water_quality_data = 1;</code>
   */
  ds.analysis.AnalysisDataOrBuilder getWaterQualityDataOrBuilder(
      int index);
}
