// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterquality.proto

package ds.waterquality;

public interface WaterQualityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterquality.WaterQualityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .waterquality.WaterQuality data = 1;</code>
   */
  java.util.List<ds.waterquality.WaterQuality> 
      getDataList();
  /**
   * <code>repeated .waterquality.WaterQuality data = 1;</code>
   */
  ds.waterquality.WaterQuality getData(int index);
  /**
   * <code>repeated .waterquality.WaterQuality data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .waterquality.WaterQuality data = 1;</code>
   */
  java.util.List<? extends ds.waterquality.WaterQualityOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .waterquality.WaterQuality data = 1;</code>
   */
  ds.waterquality.WaterQualityOrBuilder getDataOrBuilder(
      int index);
}
