// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterquality.proto

package ds.waterquality;

public interface WaterQualityStreamingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterquality.WaterQualityStreamingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>int32 duration = 2;</code>
   */
  int getDuration();
}
