// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterquality.proto

package ds.waterquality;

public final class WaterQualityProto {
  private WaterQualityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterquality_WaterQualityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterquality_WaterQualityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterquality_WaterQualityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterquality_WaterQualityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterquality_WaterQuality_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterquality_WaterQuality_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterquality_WaterQualityThresholdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterquality_WaterQualityThresholdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterquality_WaterQualityThresholdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterquality_WaterQualityThresholdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterquality_WaterQualityStreamingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterquality_WaterQualityStreamingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterquality_WaterQualityStreamingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterquality_WaterQualityStreamingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022waterquality.proto\022\014waterquality\"M\n\023Wa" +
      "terQualityRequest\022\020\n\010location\030\001 \001(\t\022\022\n\ns" +
      "tart_time\030\002 \001(\t\022\020\n\010end_time\030\003 \001(\t\"@\n\024Wat" +
      "erQualityResponse\022(\n\004data\030\001 \003(\0132\032.waterq" +
      "uality.WaterQuality\"\201\001\n\014WaterQuality\022\020\n\010" +
      "location\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\t\022\n\n\002ph\030" +
      "\003 \001(\001\022\023\n\013temperature\030\004 \001(\001\022\021\n\tturbidity\030" +
      "\005 \001(\001\022\030\n\020dissolved_oxygen\030\006 \001(\001\"I\n\034Water" +
      "QualityThresholdRequest\022\020\n\010location\030\001 \001(" +
      "\t\022\027\n\017threshold_value\030\002 \001(\001\"0\n\035WaterQuali" +
      "tyThresholdResponse\022\017\n\007message\030\001 \001(\t\"B\n\034" +
      "WaterQualityStreamingRequest\022\020\n\010location" +
      "\030\001 \001(\t\022\020\n\010duration\030\002 \001(\005\"I\n\035WaterQuality" +
      "StreamingResponse\022(\n\004data\030\001 \001(\0132\032.waterq" +
      "uality.WaterQuality2\343\002\n\023WaterQualityServ" +
      "ice\022^\n\023GetWaterQualityData\022!.waterqualit" +
      "y.WaterQualityRequest\032\".waterquality.Wat" +
      "erQualityResponse\"\000\022u\n\030SetWaterQualityTh" +
      "reshold\022*.waterquality.WaterQualityThres" +
      "holdRequest\032+.waterquality.WaterQualityT" +
      "hresholdResponse\"\000\022u\n\026StreamWaterQuality" +
      "Data\022*.waterquality.WaterQualityStreamin" +
      "gRequest\032+.waterquality.WaterQualityStre" +
      "amingResponse\"\0000\001B&\n\017ds.waterqualityB\021Wa" +
      "terQualityProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_waterquality_WaterQualityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_waterquality_WaterQualityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterquality_WaterQualityRequest_descriptor,
        new java.lang.String[] { "Location", "StartTime", "EndTime", });
    internal_static_waterquality_WaterQualityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_waterquality_WaterQualityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterquality_WaterQualityResponse_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_waterquality_WaterQuality_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_waterquality_WaterQuality_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterquality_WaterQuality_descriptor,
        new java.lang.String[] { "Location", "Timestamp", "Ph", "Temperature", "Turbidity", "DissolvedOxygen", });
    internal_static_waterquality_WaterQualityThresholdRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_waterquality_WaterQualityThresholdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterquality_WaterQualityThresholdRequest_descriptor,
        new java.lang.String[] { "Location", "ThresholdValue", });
    internal_static_waterquality_WaterQualityThresholdResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_waterquality_WaterQualityThresholdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterquality_WaterQualityThresholdResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_waterquality_WaterQualityStreamingRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_waterquality_WaterQualityStreamingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterquality_WaterQualityStreamingRequest_descriptor,
        new java.lang.String[] { "Location", "Duration", });
    internal_static_waterquality_WaterQualityStreamingResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_waterquality_WaterQualityStreamingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterquality_WaterQualityStreamingResponse_descriptor,
        new java.lang.String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
