// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterquality.proto

package ds.waterquality;

public interface WaterQualityThresholdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterquality.WaterQualityThresholdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>double threshold_value = 2;</code>
   */
  double getThresholdValue();
}
