// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterquality.proto

package ds.waterquality;

public interface WaterQualityStreamingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterquality.WaterQualityStreamingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.waterquality.WaterQuality data = 1;</code>
   */
  boolean hasData();
  /**
   * <code>.waterquality.WaterQuality data = 1;</code>
   */
  ds.waterquality.WaterQuality getData();
  /**
   * <code>.waterquality.WaterQuality data = 1;</code>
   */
  ds.waterquality.WaterQualityOrBuilder getDataOrBuilder();
}
