// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package ds.airquality;

public interface AirQualityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airquality.AirQualityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .airquality.AirQuality data = 1;</code>
   */
  java.util.List<ds.airquality.AirQuality> 
      getDataList();
  /**
   * <code>repeated .airquality.AirQuality data = 1;</code>
   */
  ds.airquality.AirQuality getData(int index);
  /**
   * <code>repeated .airquality.AirQuality data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .airquality.AirQuality data = 1;</code>
   */
  java.util.List<? extends ds.airquality.AirQualityOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .airquality.AirQuality data = 1;</code>
   */
  ds.airquality.AirQualityOrBuilder getDataOrBuilder(
      int index);
}
