// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package ds.airquality;

public interface AirQualityThresholdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airquality.AirQualityThresholdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>int32 threshold_value = 2;</code>
   */
  int getThresholdValue();
}
