// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package ds.airquality;

public interface AirQualityMonitoringResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airquality.AirQualityMonitoringResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.airquality.AirQuality data = 1;</code>
   */
  boolean hasData();
  /**
   * <code>.airquality.AirQuality data = 1;</code>
   */
  ds.airquality.AirQuality getData();
  /**
   * <code>.airquality.AirQuality data = 1;</code>
   */
  ds.airquality.AirQualityOrBuilder getDataOrBuilder();
}
